---
apiVersion: v1
kind: Service
metadata:
  name: webhook-webhook-service
  namespace: webhook-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager