---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-manager-role
rules:
- apiGroups:
  - virtualkubelet.liqo.io
  resources:
  - shadowpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sharing.liqo.io
  resources:
  - resourceoffers
  verbs:
  - get
  - list
  - watch