---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-serving-cert
  namespace: webhook-system
spec:
  dnsNames:
  - webhook-webhook-service.webhook-system.svc
  - webhook-webhook-service.webhook-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: webhook-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-selfsigned-issuer
  namespace: webhook-system
spec:
  selfSigned: {}