apiVersion: virtualkubelet.liqo.io/v1alpha1
kind: ShadowPod
metadata:
  name: shadowpod-sample
  annotations: 
    shadowpod-webhook: allowed
spec:
  pod:
    containers:
    - name: nginx-quota
      image: nginx
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "256M"
          cpu: "1000m"
        requests:
          memory: "40Mi"
          cpu: "400m"